services:
  app:
    image:
      ghcr.io/bbsebb/ashs-new:${IMAGE_TAG:-latest}
    container_name: spring-app-staging
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=staging
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db-staging:5432/ashs_db
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - PAGE_ACCESS_TOKEN=${PAGE_ACCESS_TOKEN}
      - APP_CORS_ALLOWED_ORIGINS=${APP_CORS_ALLOWED_ORIGINS}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - SPRING_FLYWAY_ENABLED=true
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    container_name: postgres-db-staging
    environment:
      - POSTGRES_DB=ashs_db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    healthcheck:
      test: [ "CMD-SHELL", 'pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"' ]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend-app:
    image: ghcr.io/bbsebb/ashs-new-frontend-app:${IMAGE_TAG:-latest}
    container_name: angular-app-staging
    ports:
      - "8081:80"

  frontend-admin:
    image: ghcr.io/bbsebb/ashs-new-frontend-admin:${IMAGE_TAG:-latest}
    container_name: angular-admin-staging
    ports:
      - "8082:80"
