version: '3.8'
services:
  app:
    image: ghcr.io/bbsebb/ashs-new:d7d6e9de30064a62fff8aacd4041b709461ae130
    container_name: spring-app-staging
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/myapp
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
      - PAGE_ACCESS_TOKEN=${PAGE_ACCESS_TOKEN}
      - SPRING_FLYWAY_ENABLED=true
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    container_name: postgres-db-staging
    environment:
      - POSTGRES_DB=myapp
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    healthcheck:
      test: ["CMD-SHELL", 'pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"']
      interval: 5s
      timeout: 5s
      retries: 5

  frontend-app:
    image: ghcr.io/bbsebb/ashs-new-frontend-app:d7d6e9de30064a62fff8aacd4041b709461ae130
    container_name: angular-app-staging
    ports:
      - "8081:80"

  frontend-admin:
    image: ghcr.io/bbsebb/ashs-new-frontend-admin:d7d6e9de30064a62fff8aacd4041b709461ae130
    container_name: angular-admin-staging
    ports:
      - "8082:80"
