services:
  postgres:
    container_name: postgres-ashs-new
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=ashs-db'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
  # --- SERVEUR D'AUTHENTIFICATION ---
