CREATE SCHEMA IF NOT EXISTS hall_schema;
CREATE SCHEMA IF NOT EXISTS staff_schema;
CREATE SCHEMA IF NOT EXISTS team_schema;
CREATE SCHEMA IF NOT EXISTS season_schema;
CREATE SCHEMA IF NOT EXISTS flyway_schema;
CREATE SCHEMA IF NOT EXISTS modulith_schema;
