spring:
  config:
    activate:
      on-profile: dev

  docker:
    compose:
      enabled: true
      file: ./backend/compose.yaml

  flyway:
    enabled: true
    create-schemas: true
    clean-disabled: false
    validate-on-migrate: false

contact:
  administrator:
    email:
      address: sebastien.burckhardt@hoenheimsports.fr


logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.results: TRACE
    fr.hoenheimsports: DEBUG