spring:
  application:
    name: ashs-backend

  jackson:
    time-zone: Europe/Paris

  http:
    client:
      service:
        group:
          meta-client:
            base-url: https://graph.facebook.com

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  flyway:
    enabled: true
    schemas: hall_schema, staff_schema, team_schema, flyway_schema, season_schema, modulith_schema, membership_schema
    default-schema: flyway_schema

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

  modulith:
    runtime:
      flyway-enabled: true
    events:
      jdbc:
        schema: modulith_schema
        schema-initialization:
          enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          # L'URL exacte de ton Realm Keycloak
          issuer-uri: ${RESOURCE_SERVER_ISSUER_URI:http://localhost:8079/realms/ashs}

springdoc:
  api-docs:
    path: /v3/api-docs
  scalar:
    enabled: true
    path: /scalar
  swagger-ui:
    path: /swagger-ui.html

meta:
  page-access-token: ${PAGE_ACCESS_TOKEN}
  version: v24.0
  page-id: 500999826723464

app:
  cors:
    allowed-headers: "Authorization,Content-Type,Accept,Origin,X-Requested-With"
    allowed-methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:4200}
  upload:
    dir: "uploads/"

contact:
  administrator:
    email:
      address: ${CONTACT_ADMIN_EMAIL:admin@hoenheimsports.fr}

sumup:
  api-key: ${SUMUP_API_KEY}
  merchant-email: ${SUMUP_MERCHANT_EMAIL}
  return-url: ${SUMUP_RETURN_URL:http://localhost:4200/membership/payment-success}
