spring:
  config:
    activate:
      on-profile: prod

  docker:
    compose:
      enabled: false

  datasource:
    # 'postgres-prod' doit correspondre au nom du service BDD dans le docker-compose du VPS
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  flyway:
    clean-disabled: true # CRITIQUE : Empêche la suppression des données en prod
    validate-on-migrate: true

  jpa:
    open-in-view: false

contact:
  administrator:
    email:
      address: president@hoenheimsports.fr

management:
  tracing:
    sampling:
      probability: 0.1
  otlp:
    metrics:
      export:
        url: ${MANAGEMENT_OTLP_METRICS_EXPORT_URL:http://localhost:4318/v1/metrics}
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${MANAGEMENT_OTLP_TRACING_ENDPOINT:http://localhost:4318/v1/traces}
    logging:
      export:
        otlp:
          endpoint: ${MANAGEMENT_OTLP_LOGGING_ENDPOINT:http://localhost:4318/v1/logs}

logging:
  level:
    # On réduit drastiquement les logs pour ne pas saturer l'espace disque du VPS
    root: WARN
    fr.hoenheimsports: INFO

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
  scalar:
    enabled: false