spring:
  application:
    name: ashs-backend
  docker:
    compose:
      file: ./backend/compose.yaml
  http:
    client:
      service:
        group:
          meta-client:
            base-url: https://graph.facebook.com

  jackson:
    time-zone: Europe/Paris

  flyway:
    create-schemas: true
    schemas: hall_schema, staff_schema, team_schema, flyway_schema , season_schema
    default-schema: flyway_schema
    #    en developpement
    validate-on-migrate: true
    clean-disabled: false

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

  modulith:
    runtime:
      flyway-enabled: true

meta:
  page-access-token: ${PAGE_ACCESS_TOKEN}
  version: v24.0
  page-id: 500999826723464

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:4200}
    allowed-methods: ${APP_CORS_ALLOWED_METHODS:GET,POST,PUT,PATCH,DELETE,OPTIONS}
    allowed-headers: ${APP_CORS_ALLOWED_HEADERS:Authorization,Content-Type,Accept,Origin,X-Requested-With}
  upload:
    dir: ${APP_UPLOAD_DIR:uploads/}

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.results: TRACE
    fr.hoenheimsports: DEBUG
