/**
 * Represents a RFC 7807 Problem Details object for HTTP APIs.
 * Used to carry machine-readable details of errors in a HTTP response.
 */
export class ProblemDetail {
  /** The type of the problem */
  type?: string;
  /** A short, human-readable summary of the problem type */
  title?: string;
  /** The HTTP status code generated by the origin server for this occurrence of the problem */
  status?: number;
  /** A human-readable explanation specific to this occurrence of the problem */
  detail?: string;
  /** A URI reference that identifies the specific occurrence of the problem */
  instance?: string;
  /**
   * Field-specific validation errors.
   * Maps field names to their respective error messages.
   * Initialized by default to avoid null checks.
   */
  fieldErrors: Record<string, string> = {};
  /**
   * Global validation errors not tied to a specific field.
   * Maps error names to their respective messages.
   */
  globalErrors: Record<string, string> = {};

  /**
   * Constructs a new ProblemDetail instance.
   * @param data Optional partial data to initialize the instance.
   */
  constructor(data?: Partial<ProblemDetail>) {
    if (data) {
      Object.assign(this, data);
    }
  }


  /**
   * Checks if a specific field has a validation error.
   * @param fieldName The name of the field to check.
   * @returns True if the field has an error, false otherwise.
   */
  hasFieldError(fieldName: string): boolean {
    return this.fieldErrors && Object.prototype.hasOwnProperty.call(this.fieldErrors, fieldName);
  }

  /**
   * Checks if there are any field validation errors.
   * @returns True if at least one field error exists.
   */
  hasAnyFieldError(): boolean {
    return Object.keys(this.fieldErrors || {}).length > 0;
  }

  /**
   * Checks if there are any global validation errors.
   * @returns True if at least one global error exists.
   */
  hasAnyGlobalError(): boolean {
    return Object.keys(this.globalErrors || {}).length > 0;
  }



  /**
   * Retrieves the error message for a specific field.
   * @param fieldName The name of the field.
   * @returns The error message string or null if no error is found.
   */
  getFieldError(fieldName: string): string | null {
    return this.hasFieldError(fieldName) ? this.fieldErrors[fieldName] : null;
  }

  /**
   * Checks if a specific global error exists.
   * @param globalName The name of the global error.
   * @returns True if the global error exists.
   */
  hasGlobalError(globalName: string): boolean {
    return this.fieldErrors && Object.prototype.hasOwnProperty.call(this.fieldErrors, globalName);
  }

  /**
   * Retrieves the message for a specific global error.
   * @param globalName The name of the global error.
   * @returns The error message string or null if no error is found.
   */
  getGlobalError(globalName: string): string | null {
    return this.hasFieldError(globalName) ? this.fieldErrors[globalName] : null;
  }



  /**
   * Checks if there are any validation errors (field or global).
   * @returns True if any validation error is present.
   */
  hasAnyValidationError(): boolean {
    return this.hasAnyFieldError() || this.hasAnyGlobalError();
  }



  /**
   * Formats a complete message for the user.
   * @returns A descriptive error message based on the problem details.
   */
  getFormattedMessage(): string {
    if (this.status === 400 && this.hasAnyValidationError()) {
      return `Validation échouée : ${Object.keys(this.fieldErrors).length} erreur(s) détectée(s).`;
    }
    return this.detail || this.title || 'Une erreur inconnue est survenue';
  }
}
